### ISSUE TITLE
关于highstcok一些问题

### ISSUE THREAD

**Issue by saga7878** [friends110110/stock_Trend_Kline_chart#1]
您好，我最近准备做一个关于K线、分时图的项目，搜了很多资料，找到您写的博客和github地址，有一些问题想请教您，在移动端上 我应该如何实现长按事件显示固定位置的tooltip，单指滑动时k线平移呢？如果您看到了 希望您有时间能够回复一下，非常感谢。

**Comment by friends110110** [comment]
[参考](http://www.cnblogs.com/friends-wf/p/4480170.html)   tooltip需要自己定制化，因为库中默认的tooltip可能无法满足我们的需求。详看 var tooltipChart = {//  方面的关联，单指滑动时 可以捕捉手指的(x,y)数值的，然后 等比例 扩展到图标上 就能找到手指点了。
